spring:
  application:
    name: track-service
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: {TRACK DATABASE}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod
kafka:
  InputTopic: trade_events
  OutputTopic: trade_data
  servers: {KAFKA SERVER ONE},{KAFKA SERVER TWO},{KAFKA SERVER THREE}
  acks: all
  extractor: extractor
  processor: processor
server:
  port: 8000
binance:
  token: {TOKEN}
eureka:
  client:
    service-url:
      defaultZone: {EUREKA URL}