spring:
    jpa:
        database: mysql
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

    datasource:
        url: jdbc:mysql://localhost:3306/track?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
        active: local
kafka:
    topic:
        input: trade_events
        output: trade_data
    servers: localhost:9091,localhost:9092,localhost:9093
    acks: all
    extractor:
        id: extractor
    processor:
        id: processor
server:
    port: 8000

binance:
    apiKey: KEY
    secretKey: KEY
    token: KEY