spring:
    jpa:
        database: mysql
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
    kafka:
        consumer:
            group-id: data-api
            session-timeout-ms: 25000
            max-poll-interval-ms: 600000
            enable-auto-commit: false
            max-poll-records: 30
        bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    datasource:
        url: jdbc:mysql://localhost:3306/track?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
        active: local
    thymeleaf:
        prefix: classpath:/templates/
server:
    port: 8002

topic: trade_data