spring:
  application:
    name: display-service
  kafka:
    consumer:
      group-id: data-api
      session-timeout-ms: 25000
      max-poll-interval-ms: 600000
      enable-auto-commit: false
      max-poll-records: 30
    bootstrap-servers: {KAFKA SERVER ONE},{KAFKA SERVER TWO},{KAFKA SERVER THREE}
  profiles:
    active: prod
  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8002

topic: trade_data

eureka:
  client:
    service-url:
      defaultZone: {EUREKA URL}