spring:
  kafka:
    consumer:
      group-id: data-api
      session-timeout-ms: 25000
      max-poll-interval-ms: 600000
      enable-auto-commit: false
      max-poll-records: 30
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
server:
  port: 8002
topic: trade_data