spring:
  application:
    name: message-service
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: {MESSAGE DATABASE}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  thymeleaf:
    prefix: classpath:/templates/
server:
  port: 8003
telegram:
  token: {TOKEN}
  charId: {CHAT ID}
  name: {BOT NAME}
eureka:
  client:
    service-url:
      defaultZone: {EUREKA URL}